---
repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: system
        entry: shellcheck --external-sources
        types: [shell]
      - id: shfmt
        name: shfmt
        language: system
        entry: shfmt --indent 4 --diff --write
        types: [shell]
      - id: prettier
        name: prettier
        language: system
        entry: node airport-lisk/node_modules/prettier/bin-prettier.js --write
        files: \.(js|css|html|json|cjs|mjs)$
